#!/usr/bin/expect -f

set passphrase $env(GPG_PASSPHRASE)
set sign_key_id $env(SIGN_KEY_ID)
set workspace $env(WORKSPACE)

set debfile [exec find $CI_PROJECT_DIR/outcomes/pkg/ -name *.deb -type f]

spawn debsigs --sign=origin -k $sign_key_id $debfile
expect "Enter passphrase: "
send -- "$passphrase\r"
expect eof
