---
- name: Configure .env file used by docker-compose
  copy:
    content: |
      AGENT_DOCKER_REPO={{ agent_docker_repo }}
      AGENT_VERSION={{ agent_current_branch }}
      DOCKER_HOST_IP={{ ansible_docker0['ipv4']['address'] }}
      STACKSTATE_BRANCH={{ stackstate_branch }}
    dest: /home/ubuntu/.env

- name: Check if nginx service already exists, otherwise create it
  shell: "docker service ps nginx"
  register: nginx_status
  ignore_errors: true

- name: Create a global nginx service
  shell: "docker service create --name nginx --mode global nginx"
  when: nginx_status.rc != 0
  run_once: true

- name: Installing docker in Ansible
  pip:
    name: docker

- name: Docker login
  docker_login:
    registry: artifactory.tooling.stackstate.io
    username: "{{ artifactory_user }}"
    password: "{{ artifactory_password }}"
    reauthorize: yes

- name: Copy docker compose file
  copy:
    src: ../../files/docker-compose.yml
    dest: /home/ubuntu/
    mode: preserve

- name: Stop docker stack
  command: docker stack rm agent
  args:
    chdir: /home/ubuntu/
  environment:
    AGENT_VERSION: "{{ agent_current_branch }}"
    STACKSTATE_BRANCH: "{{ stackstate_branch }}"

- name: Docker compose pull images (cache purposes)
  shell:
    cmd: docker-compose pull
    chdir: /home/ubuntu/
  ignore_errors: true
  register: compose

- name: Copy docker logs backup script
  copy:
    src: ../files/docker-logs.sh
    dest: /home/ubuntu/docker-logs.sh
    mode: preserve
  ignore_errors: true
  become: true
