// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "c10fe47dcf5938150abbe168065643a2261647eab6f1b9821750d2431fa38ff7")
