stages:
  - build
  - fallback-manual

variables:
  DOCKER_REGISTRY: docker.io
  QUAY_REGISTRY: quay.io
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo "${docker_password}" | docker login --username=${docker_user} --password-stdin ${DOCKER_REGISTRY}
  - echo "${quay_password}" | docker login --username=${quay_user} --password-stdin ${QUAY_REGISTRY}
  - apk add make

.docker_build_base: &docker_build_base
  image: artifactory.tooling.stackstate.io/docker-virtual/docker:18.06.0
  services:
    - name: artifactory.tooling.stackstate.io/docker-virtual/docker:18.09-dind
      alias: docker

books-app:
  <<: *docker_build_base
  stage: build
  script:
    - cd .ci-builders/books-app
    - BASE_RUNNER_TAG="books-app-$(date +%Y%m%d)"
    - BUILD_TAG="trace-java-demo:${BASE_RUNNER_TAG}"
    - docker build -t "${BUILD_TAG}" .
    # tag the image, push to quay
    - QUAY_TAG="${QUAY_REGISTRY}/stackstate/${BUILD_TAG}"
    - docker tag "${BUILD_TAG}" "${QUAY_TAG}"
    - docker push "${QUAY_TAG}"
    - echo "BASE_RUNNER_TAG=$BASE_RUNNER_TAG"
    - echo "BASE_RUNNER_TAG=$BASE_RUNNER_TAG" >> $CI_PROJECT_DIR/build.env
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[build_books_app]/
      when: always
    - if: $CI_COMMIT_MESSAGE
      when: manual
      allow_failure: true

# This ensures that triggers can achieve success status if manual jobs are not executed.
ensure-success-manual:
  stage: fallback-manual
  before_script: []
  dependencies:
    - books-app
  script:
    - echo "I will succeed"
  rules:
    - when: on_success
  retry:
    max: 2
