stages:
  - build

variables:
  RUNNER_BEEST_BASE: $CI_PROJECT_DIR/.ci-builders/beest-base
  DOCKER_REGISTRY: docker.io
  QUAY_REGISTRY: quay.io
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo "${docker_password}" | docker login --username=${docker_user} --password-stdin ${DOCKER_REGISTRY}
  - echo "${quay_password}" | docker login --username=${quay_user} --password-stdin ${QUAY_REGISTRY}
  - apk add make

.docker_build_base: &docker_build_base
  image: artifactory.tooling.stackstate.io/docker-virtual/docker:18.06.0
  services:
    - name: artifactory.tooling.stackstate.io/docker-virtual/docker:18.09-dind
      alias: docker

beest-keeper:
  <<: *docker_build_base
  stage: build
  script:
    - cd $RUNNER_BEEST_BASE
    - make
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[build_runner_beest]/
      when: always
    - if: $CI_COMMIT_MESSAGE
      when: manual
      allow_failure: true
