source 'https://rubygems.org'

gem 'libyajl2', git: 'https://github.com/StackVista/libyajl2-gem.git', branch: '1.2.0-fixed-lssa', submodules: true

# Install omnibus
# Sadly, DataDog does not provide tag for release we are using, so we are forced to use commit SHA1.
# Check OMNIBUS_RUBY_VERSION in stackstate-deps.json (in root of this git repository).
gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', branch: (ENV['OMNIBUS_RUBY_VERSION'] || 'datadog-5.5.0')

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', git: 'https://github.com/DataDog/omnibus-software.git', branch: (ENV['OMNIBUS_SOFTWARE_VERSION'] || 'master')


gem 'mixlib-cli', '~> 1.7.0'

