source 'https://rubygems.org'

# Install omnibus
gem 'chef-sugar', git: 'https://github.com/chef/chef-sugar.git', tag: 'v3.6.0'
# Sadly, DataDog does not provide tag for release we are using, so we are forced to use commit SHA1.
# Check OMNIBUS_RUBY_VERSION in stackstate-deps.json (in root of this git repository).
gem 'omnibus', git: 'https://github.com/DataDog/omnibus-ruby.git', ref: (ENV['OMNIBUS_RUBY_VERSION'] || 'datadog-5.5.0')

gem 'mixlib-cli', '~> 1.7.0'
