---
agent_current_branch: "{{ lookup('env', 'AGENT_CURRENT_BRANCH') or AGENT_CURRENT_BRANCH }}"
agent_docker_repo: "{{ lookup('env', 'STS_DOCKER_TEST_REPO') or STS_DOCKER_TEST_REPO }}"
cluster_agent_docker_repo: "{{ lookup('env', 'STS_DOCKER_TEST_REPO_CLUSTER') or STS_DOCKER_TEST_REPO_CLUSTER }}"
quay_password: "{{ lookup('env', 'quay_password') or QUAY_PASSWORD }}"
quay_user: "{{ lookup('env', 'quay_user') or QUAY_USER }}"
stackstate_branch: "{{ lookup('env', 'STACKSTATE_BRANCH') or STACKSTATE_BRANCH }}"

dnat_service_port: 321
dnat_server_port: 123
container_to_container_server_port: 234
headless_service_port: 543
namespace: "{{ agent_current_branch.replace('.','-').replace('_','-') | lower }}"
cluster_name: "{{ namespace }}"

kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
kubecontext: "{{ yard_id }}"
