- name: Prepare Kubernetes Stackstate
  hosts: local
  gather_facts: false
  roles:
    - role: "{{ bees_path }}/k8s-stackstate"
      vars:
        sts_ingress: KOPS
    - role: "{{ bees_path }}/otel-lambda"

- name: Prepare VM Agent
  hosts: agent
  gather_facts: true
  roles:
    - role: "{{ bees_path }}/ec2-agent"
