generate-values:
  license: {{ stackstate_license }}
  pull-user: {{ artifactory_user }}
  pull-password: {{ artifactory_password }}
  pull-policy: IfNotPresent
  pull-registry: artifactory.tooling.stackstate.io/docker-virtual
  profile: development-split
  ingress: K3D
  install-agent: false
  base-url: https://localhost/
  default-password:  admin
  api-password: api-admin
  extra-api-key: xxx #  <api-key for champagne-intake, see 1password> # in case you want to receive the same traffic as nightly champagne
  override-sts-image-tag: master
