apiVersion: v1
kind: Pod
metadata:
  name: pod-localhost
  labels:
    test: pod-localhost
spec:
  containers:
    - image: jgkamat/netcat
      imagePullPolicy: IfNotPresent
      name: server
      command: ["/bin/bash", "-c", "nc -l -p 234 > /dev/null"]
    - image: jgkamat/netcat
      imagePullPolicy: IfNotPresent
      name: client
      command: ["/bin/bash", "-c", "while echo y; do sleep 0.1; done | nc localhost 234"]
