variable "environment" {}
variable "vpc_id" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "k8s_cluster_name" {}
variable "k8s_version" {}
variable "k8s_runtime" {}
variable "k8s_node_type" {}
variable "k8s_size" {}
