---
- name: StackState prepare tasks
  tags: prepare
  block:
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: stable
      repo_url: "https://charts.helm.sh/stable"

  - name: Add stackstate-internal chart repo
    kubernetes.core.helm_repository:
      name: stackstate-internal
      repo_url: "https://helm-internal.stackstate.io"

  - name: Add stackstate chart repo
    kubernetes.core.helm_repository:
      name: stackstate
      repo_url: "https://helm.stackstate.io"


  - name: Generate sts-toolbox config
    ansible.builtin.template:
      src: sts-toolbox-config.yaml
      dest: "{{ playbook_dir }}/sts-toolbox.yml"

  - name: Generate StackState values
    ansible.builtin.command:
      cmd: sts-toolbox generate-values --config "{{ playbook_dir }}/sts-toolbox.yml" --output "{{ playbook_dir }}/stackstate-values.yml"


  - name: Deploy stackstate chart using values files
    kubernetes.core.helm:
      context: "{{ kubecontext }}"
      chart_ref: stackstate-internal/stackstate
      chart_version: "{{ stackstate_helm_chart }}"
      release_name: stackstate
      release_namespace: "{{ namespace }}"
      create_namespace: true
      update_repo_cache: true
      wait: yes
      wait_timeout: 10m
      values_files:
        - "{{ playbook_dir }}/stackstate-values.yml"
      values:
        stackstate:
          components:
            e2es:
              replicaCount: 0
            mm2es:
              replicaCount: 0
            problemProducer:
              replicaCount: 0
            trace2es:
              replicaCount: 0


## Cleanup

- name: StackState cleanup tasks
  tags: cleanup
  block:
  - name: Undeploy stackstate
    kubernetes.core.helm:
      context: "{{ kubecontext }}"
      release_name: stackstate
      release_namespace: "{{ namespace }}"
      state: absent
      wait: true

  - name: Delete namespace '{{namespace}}'
    kubernetes.core.k8s:
      context: "{{ kubecontext }}"
      api_version: v1
      kind: Namespace
      name: "{{ namespace }}"
      state: absent
      wait: yes
