---
- name: Apply manifests for test connections
  command: kubectl --context={{ kubecontext }} -n={{ test_namespace }} apply -f {{ item }}
  loop:
    - pod-to-service-cluster-ip.yaml
    - pod-localhost.yaml
    - pod-to-pod-headless.yaml
    - pod-http-metrics.yaml
  args:
    chdir: "{{ role_path }}/files/test_connections"

- name: Wait for the pod-to-service-cluster-ip scenario to become ready
  command: kubectl --context={{ kubecontext }} -n={{ test_namespace }} wait --all --for=condition=Ready --timeout=360s -l test={{ item }} pod
  loop:
    - pod-to-service-cluster-ip
    - pod-localhost
    - pod-to-pod-headless
    - pod-http-metrics
