---
- name: Set quay.io registry key fact
  set_fact:
    quay_registry_key:
      auths:
        quay.io:
          auth: "{{ ':'.join((quay_user, quay_password)) | b64encode }}"

- name: Create docker secret to allow pulling from quay.io registry
  kubernetes.core.k8s:
    context: "{{ kubecontext }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: "{{ quay_registry_key | to_json | b64encode }}"
      metadata:
        name: "docker-registry-key"
        namespace: "{{ monitoring_namespace }}"
      type: "kubernetes.io/dockerconfigjson"
