- name: Kubernetes Stackstate
  hosts: local
  gather_facts: false
  roles:
    - role: "{{ bees_path }}/k8s-stackstate"
      vars:
        sts_ingress: KOPS

- name: VM Splunk
  hosts: splunk
  gather_facts: false
  roles:
    - role: "{{ bees_path }}/ec2-splunk"

- name: VM Agent
  hosts: splunk
  gather_facts: true
  roles:
    - role: "{{ bees_path }}/ec2-agent"
