# No need to disable the StackState instance if you enable the Simulator, The data will be forwarded form the Simulator
- name: Kubernetes Stackstate
  hosts: local
  gather_facts: false
  roles:
    - role: "{{ bees_path }}/k8s-stackstate"
      vars:
        sts_ingress: KOPS

# We always run the ec2-simulator even if it is disabled to clean up if it goes from enabled to disabled
- name: StackState Simulator (Debugging)
  hosts: splunk
  gather_facts: true
  roles:
    - role: "{{ bees_path }}/ec2-simulator"

- name: VM Splunk
  hosts: splunk
  gather_facts: false
  roles:
    - role: "{{ bees_path }}/ec2-splunk"

# The Agent will automatically point to the simulator if it is enabled
- name: VM Agent
  hosts: splunk
  gather_facts: true
  roles:
    - role: "{{ bees_path }}/ec2-agent"
