---
artifactory_user: "{{ lookup('env', 'registry_user') or REGISTRY_USER }}"
artifactory_password: "{{ lookup('env', 'registry_password') or REGISTRY_PASSWORD }}"

stackstate_helm_chart_version: "{{ lookup('env', 'STACKSTATE_HELM_CHART_VERSION') }}"
stackstate_platform_version: "{{ lookup('env', 'STACKSTATE_PLATFORM_VERSION') }}"
stackstate_license: "{{ lookup('env', 'STACKSTATE_LICENSE') or STACKSTATE_LICENSE }}"

namespace: "{{ yard_id.replace('.','-').replace('_','-') | lower }}"
cluster_name: "sandbox-main.sandbox.stackstate.io"

kubecontext: "{{ cluster_name }}"

sts_api_key: "{{ yard_id }}"
sts_url: "https://{{ yard_id }}.{{ cluster_name }}"
