---
# tasks file for ec2-splunk
- name: Splunk Events Prepare Tasks
  tags: prepare
  become: yes
  block:
    - name: "Splunk Events Saved Search Setup"
      set_fact:
        source_type: "sts_test_data"
        saved_search_name: "events"
        saved_search_format: "table _time _bkt _cd host status description"

    - name: "Delete Splunk Events Saved Search"
      command: |
        curl -k -X DELETE -u "{{ splunk_user }}:{{ splunk_pass }}" \
        https://localhost:{{ splunk_port }}/services/saved/searches/{{ saved_search_name }}

    - name: "Create Splunk Events Saved Search"
      command: |
        curl -k -u "{{ splunk_user }}:{{ splunk_pass }}" \
        https://localhost:{{ splunk_port }}/services/saved/searches \
        -d name="{{ saved_search_name }}" \
        --data-urlencode search="sourcetype=\"{{ source_type }}\" | eval status = upper(status) | search status=critical OR status=error OR status=warning OR status=ok | {{ saved_search_format }}"
