---
# tasks file for ec2-splunk
- name: Splunk Health Prepare Tasks
  tags: prepare
  become: yes
  block:
    - name: "Splunk Health Saved Search Setup"
      set_fact:
        source_type: "sts_test_data"
        saved_search_name: "health"
        saved_search_fields: "fields check_state_id, name, health, topology_element_identifier, message"

    - name: "Delete Splunk Health Saved Search"
      command: |
        curl -k -X DELETE -u "{{ splunk_user }}:{{ splunk_pass }}" \
        https://localhost:{{ splunk_port }}/services/saved/searches/{{ saved_search_name }}

    - name: "Create Splunk Health Saved Search"
      command: |
        curl -k -u "{{ splunk_user }}:{{ splunk_pass }}" \
        https://localhost:{{ splunk_port }}/services/saved/searches \
        -d name="{{ saved_search_name }}" \
        --data-urlencode search="* | dedup check_state_id | sort - check_state_id | {{ saved_search_fields }}"
