- hosts: all

  vars_files:
    - builder_vars.yml

  tasks:

    - name: ENV | PATH
      win_path:
        elements:
          - 'C:\tools\ruby24\bin'
          - 'C:\gopath\bin'
          - 'C:\Program Files\CMake\bin\'
          - 'C:\python27-x64'
          - 'C:\python27-x64\Scripts'
          - 'C:\Program Files\Git\usr\bin'
          - 'C:\Program Files\Amazon\AWSCLI'
          - 'C:\Program Files\Mercurial;C:\Program Files (x86)\WiX Toolset v3.11\bin'

    - name: Disable defender realtime scan to speedup process
      win_command: powershell.exe -
      args:
        stdin: Set-MpPreference -DisableRealtimeMonitoring $true

    - name: ENV | GOPATH
      win_environment:
        state: present
        name: GOPATH
        value: "c:\\gopath"
        level: user

    - name: ENV | GOBIN
      win_environment:
        state: present
        name: GOBIN
        value: "c:\\gopath\\bin"
        level: user

    - name: Tune git config
      win_command: "git config --global user.email \"gitlab@windowsrunner.local\""

    - name: Tune git config
      win_command: "git config --global user.name \"Windows Gitlab Runner Instance\""

    - name: Template powershell vssetup module installation
      win_copy:
        src: files/register_vssetup.ps1
        dest: C:\

    - name: Template powershell vssetup module installation
      win_copy:
        src: files/install_vssetup.ps1
        dest: C:\

    - name: Register powershell vssetup module
      win_command: powershell.exe -File C:\register_vssetup.ps1
      register: vssetup_try1
      ignore_errors: true

    - name: Install powershell vssetup module
      win_command: powershell.exe -File C:\install_vssetup.ps1
