---
agent_current_branch: "{{ lookup('env', 'AGENT_CURRENT_BRANCH') or AGENT_CURRENT_BRANCH }}"
agent_current_branch_ref: "{{ lookup('env', 'AGENT_CURRENT_BRANCH_REF') or AGENT_CURRENT_BRANCH_REF }}"
agent_repo_url: "https://{{ lookup('env', 'STS_AWS_TEST_BUCKET') or STS_AWS_TEST_BUCKET }}.s3.amazonaws.com"
agent_tag_extension: "{{ lookup('env', 'AGENT_TAG_EXTENSION') }}"

artifactory_user: "{{ lookup('env', 'artifactory_user') or ARTIFACTORY_USER }}"
artifactory_password: "{{ lookup('env', 'artifactory_password') or ARTIFACTORY_PASSWORD }}"

stackstate_helm_chart_version: "{{ lookup('env', 'STACKSTATE_HELM_CHART_VERSION') }}"
stackstate_platform_version: "{{ lookup('env', 'STACKSTATE_PLATFORM_VERSION') }}"
stackstate_license: "{{ lookup('env', 'STACKSTATE_LICENSE') or STACKSTATE_LICENSE }}"

namespace: "{{ yard_id.replace('.','-').replace('_','-') | lower }}"
cluster_name: "sandbox-main.sandbox.stackstate.io"

kubecontext: "{{ cluster_name }}"

sts_api_key: "{{ yard_id }}"
sts_url: "https://{{ yard_id }}.{{ cluster_name }}"
