---
- name: StackState Agent prepare tasks
  tags: prepare
  block:
    - name: Install stackstate-agent
      shell: "curl -o- {{ agent_repo_url }}/install.sh | bash"
      register: agent_install_result
      until: agent_install_result is not failed
      retries: 5
      delay: 60
      environment:
        STS_API_KEY: "{{ sts_api_key }}"
        STS_URL: "{{ sts_url }}/receiver/stsAgent"
        STS_HOSTNAME: "{{ inventory_hostname }}"
        CODE_NAME: "{{ agent_current_branch }}"
        SKIP_SSL_VALIDATION: "false"

    - include_tasks: aws.yml
      when: aws_integration is defined

    - include_tasks: setup_sample_check.yml
      when: agent_integration_sample_v2 is defined
      vars:
        check_name: "agent_integration_sample_v2"

    - include_tasks: setup_sample_check.yml
      when: agent_integration_sample_v2_stateful is defined
      vars:
        check_name: "agent_integration_sample_v2_stateful"

    - include_tasks: setup_sample_check.yml
      when: agent_integration_sample_v2_transactional is defined
      vars:
        check_name: "agent_integration_sample_v2_transactional"

    - name: Restart stackstate-agent
      become: yes
      ansible.builtin.service:
        name: stackstate-agent
        state: restarted


## Cleanup

- name: StackState Agent cleanup tasks
  tags: cleanup
  ignore_errors: yes
  block:
    - name: Uninstall stackstate-agent
      become: yes
      apt:
        pkg: stackstate-agent
        state: absent

    - name: Remove configurations
      become: yes
      file:
        path: /etc/stackstate-agent
        state: absent
