---
- name: My Agent Integration Sample prepare tasks
  tags: prepare
  block:
    - name: Copy check file
      become: yes
      ansible.builtin.copy:
        src: my_agent_integration_sample.py
        dest: /etc/stackstate-agent/checks.d/my_agent_integration_sample.py
        owner: stackstate-agent
        group: stackstate-agent
        mode: '0644'
    - name: Create my_agent_integration_sample.d folder
      become: yes
      file:
        path: /etc/stackstate-agent/conf.d/my_agent_integration_sample.d
        recurse: yes
        state: directory
        owner: stackstate-agent
        group: stackstate-agent
        mode: '0755'
    - name: Configure Agent Integration Sample check
      become: yes
      ansible.builtin.template:
        src: my_agent_integration_sample_conf.j2.yml
        dest: /etc/stackstate-agent/conf.d/my_agent_integration_sample.d/conf.yaml
        owner: stackstate-agent
        group: stackstate-agent
        mode: '0644'
