---
- name: Prepare Receiver
  hosts: receiver
  gather_facts: true
  tasks:
    - include_tasks: ../../bees/receiver.yml  # TODO switch to ansible role

- name: Prepare Kubernetes Cluster
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - include_tasks: ../../bees/eks_agent.yml  # TODO switch to ansible role
