stackstate:
  apiKey: {{ sts_api_key }}
  url: {{ sts_url }}/receiver/stsAgent
  cluster:
    name: {{ cluster_name }}
agent:
  containers:
    agent:
      image:
        tag: {{ agent_current_branch }}
        repository: "stackstate/{{ agent_docker_repo }}"
    processAgent:
      image:
        tag: {{ process_agent_branch }}
        repository: "stackstate/{{process_agent_repo}}"
clusterAgent:
  image:
    tag: {{ agent_current_branch }}
    repository: "stackstate/{{cluster_agent_docker_repo}}"
clusterChecks:
  image:
    tag: {{agent_current_branch}}
    repository: "stackstate/{{agent_docker_repo}}"
