stackstate:
  apiKey: {{ sts_api_key }}
  url: {{ sts_url }}/receiver/stsAgent
  cluster:
    name: {{ cluster_name }}
all:
  hardening:
    enabled: true
nodeAgent:
  containers:
    agent:
      image:
        tag: "{{ agent_current_branch_ref }}-slim-instrumented"
        repository: "stackstate/{{ agent_docker_repo }}"
        pullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command: [ "/bin/sh", "-c", "echo 'Giving slim.ai monitor time to submit data...'; sleep 120" ]
        terminationGracePeriodSeconds: 240
    processAgent:
      image:
        tag: {{ process_agent_branch }}
        repository: "stackstate/{{ process_agent_repo }}"
        pullPolicy: Always
clusterAgent:
  image:
    tag: "{{ agent_current_branch_ref }}-slim-instrumented"
    repository: "stackstate/{{ cluster_agent_docker_repo }}"
    pullPolicy: Always
  lifecycle:
    preStop:
      exec:
        command: [ "/bin/sh", "-c", "echo 'Giving slim.ai monitor time to submit data...'; sleep 120" ]
    terminationGracePeriodSeconds: 240
checksAgent:
  image:
    tag: "{{ agent_current_branch_ref }}-slim-instrumented"
    repository: "stackstate/{{ agent_docker_repo }}"
    pullPolicy: Always
  lifecycle:
    preStop:
      exec:
        command: [ "/bin/sh", "-c", "echo 'Giving slim.ai monitor time to submit data...'; sleep 120" ]
    terminationGracePeriodSeconds: 240
