stackstate:
  apiKey: {{ sts_api_key }}
  url: {{ sts_url }}/receiver/stsAgent
  cluster:
    name: {{ cluster_name }}
all:
  hardening:
    enabled: true
nodeAgent:
  containers:
    agent:
      image:
        tag: "{{ agent_current_branch_ref }}-slim-instrumented"
        repository: "stackstate/{{ agent_docker_repo }}"
        pullPolicy: Always
    processAgent:
      image:
        tag: {{ process_agent_branch }}
        repository: "stackstate/{{ process_agent_repo }}"
        pullPolicy: Always
clusterAgent:
  image:
    tag: "{{ agent_current_branch_ref }}-slim-instrumented"
    repository: "stackstate/{{ cluster_agent_docker_repo }}"
    pullPolicy: Always
checksAgent:
  image:
    tag: "{{ agent_current_branch_ref }}-slim-instrumented"
    repository: "stackstate/{{ agent_docker_repo }}"
    pullPolicy: Always
