---
agent_current_branch: "{{ lookup('env', 'AGENT_CURRENT_BRANCH') or AGENT_CURRENT_BRANCH }}"
agent_docker_repo: "{{ lookup('env', 'STS_DOCKER_TEST_REPO') or STS_DOCKER_TEST_REPO }}"
process_agent_branch: "{{ lookup('env', 'PROCESS_AGENT_BRANCH') or 'master' }}"
process_agent_repo: "{{ lookup('env', 'PROCESS_AGENT_TEST_REPO') or PROCESS_AGENT_TEST_REPO }}"
cluster_agent_docker_repo: "{{ lookup('env', 'STS_DOCKER_TEST_REPO_CLUSTER') or STS_DOCKER_TEST_REPO_CLUSTER }}"

quay_password: "{{ lookup('env', 'quay_password') or QUAY_PASSWORD }}"
quay_user: "{{ lookup('env', 'quay_user') or QUAY_USER }}"

artifactory_user: "{{ lookup('env', 'artifactory_user') or ARTIFACTORY_USER }}"
artifactory_password: "{{ lookup('env', 'artifactory_password') or ARTIFACTORY_PASSWORD }}"

stackstate_branch: "{{ lookup('env', 'STACKSTATE_BRANCH') or STACKSTATE_BRANCH }}"
stackstate_helm_chart_version: "{{ lookup('env', 'STACKSTATE_HELM_CHART_VERSION') or STACKSTATE_HELM_CHART_VERSION }}"
stackstate_license: "{{ lookup('env', 'STACKSTATE_LICENSE') or STACKSTATE_LICENSE }}"

namespace: "{{ yard_id.replace('.','-').replace('_','-') | lower }}"
cluster_name: "sandbox-main.sandbox.stackstate.io"

kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
kubecontext: "{{ cluster_name }}"

sts_api_key: "{{ yard_id }}"
sts_url: "https://{{ yard_id }}.{{ cluster_name }}"

agent_helm_chart_version: "{{ lookup('env', 'AGENT_HELM_CHART_VERSION') or 'latest' }}"
