---
- hosts: local
  gather_facts: false
  tags: stackstate
  roles:
    - role: "{{ bees_path }}/k8s-stackstate"
      when: ("stackstate" in only) or only | length == 0
      vars:
        sts_ingress: KOPS
        kubecontext: "{{ stackstate_kubecontext }}"
        cluster_name: "{{ stackstate_cluster_name }}"
        namespace: "{{ test_namespace }}"
        k8s_integration:
          cluster_name: "{{ agent_cluster_name }}"
    - role: "{{ bees_path }}/k8s-agent"
      when: ("stackstate" in only) or only | length == 0
      vars:
        kubecontext: "{{ agent_kubecontext }}"
        cluster_name: "{{ agent_cluster_name }}"
