---
- name: StackPack prepare tasks
  tags: prepare
  block:
  - name: Install stackstate-agent-v2 StackPack
    kubernetes.core.k8s_exec:
      context: "{{ kubecontext }}"
      namespace: "{{ namespace }}"
      pod: stackstate-cli
      command: python -m stackstate_cli.cli stackpack install stackstate-agent-v2

  - name: Install kubernetes StackPack
    kubernetes.core.k8s_exec:
      context: "{{ kubecontext }}"
      namespace: "{{ namespace }}"
      pod: stackstate-cli
      command: python -m stackstate_cli.cli stackpack install kubernetes -p kubernetes_cluster_name "{{ cluster_name }}"
