---
- name: Apply the pod-to-service-cluster-ip scenario
  command: kubectl --context={{ kubecontext }} -n={{ namespace }} apply -f pod-to-service-cluster-ip.yaml
  args:
    chdir: "{{ ansibleTasksDir }}/kubectl/test_connections"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
